name: importGR

on:
  #schedule:
  #  - cron: '30 16 * * *'  # Runs at 16:30 UTC, which is 10:00 PM IST

  push:
    branches: [ main ]

jobs:
  import_export:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: checkout mahagri2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahagri2024
          path: import/mahagri2024
          sparse-checkout: |
            export/orgpedia_mahagri2024

      - name: checkout mahcoop2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahcoop2024
          path: import/mahcoop2024
          sparse-checkout: |
            export/orgpedia_mahcoop2024            

      - name: list files
        run: ls -lR import

      - name: import_export
        run: import/src/import_data.py import GRs
