name: importGR

on:
  schedule:
    - cron: '30 4 * * *'  # Runs at 4:30 UTC, which is 9:30 AM IST

  #push:
  #  branches: [ main ]

jobs:
  import_export:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.8'  # specify your Python version

      - name: checkout mahadmin2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahadmin2024
          path: import/mahadmin2024
          sparse-checkout: |
            export/orgpedia_mahadmin2024

      - name: checkout mahagri2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahagri2024
          path: import/mahagri2024
          sparse-checkout: |
            export/orgpedia_mahagri2024

      - name: checkout mahbah2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahbah2024
          path: import/mahbah2024
          sparse-checkout: |
            export/orgpedia_mahbah2024

      - name: checkout mahcoop2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahcoop2024
          path: import/mahcoop2024
          sparse-checkout: |
            export/orgpedia_mahcoop2024

      - name: checkout mahdis2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahdis2024
          path: import/mahdis2024
          sparse-checkout: |
            export/orgpedia_mahdis2024

      - name: checkout mahedu2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahedu2024
          path: import/mahedu2024
          sparse-checkout: |
            export/orgpedia_mahedu2024

      - name: checkout mahenv2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahenv2024
          path: import/mahenv2024
          sparse-checkout: |
            export/orgpedia_mahenv2024

      - name: checkout mahfin2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahfin2024
          path: import/mahfin2024
          sparse-checkout: |
            export/orgpedia_mahfin2024

      - name: checkout mahfood2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahfood2024
          path: import/mahfood2024
          sparse-checkout: |
            export/orgpedia_mahfood2024

      - name: checkout mahhea2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahhea2024
          path: import/mahhea2024
          sparse-checkout: |
            export/orgpedia_mahhea2024

      - name: checkout mahhome2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahhome2024
          path: import/mahhome2024
          sparse-checkout: |
            export/orgpedia_mahhome2024

      - name: checkout mahhouse2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahhouse2024
          path: import/mahhouse2024
          sparse-checkout: |
            export/orgpedia_mahhouse2024

      - name: checkout mahind2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahind2024
          path: import/mahind2024
          sparse-checkout: |
            export/orgpedia_mahind2024

      - name: checkout mahit2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahit2024
          path: import/mahit2024
          sparse-checkout: |
            export/orgpedia_mahit2024

      - name: checkout mahlaw2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahlaw2024
          path: import/mahlaw2024
          sparse-checkout: |
            export/orgpedia_mahlaw2024

      - name: checkout mahmar2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahmar2024
          path: import/mahmar2024
          sparse-checkout: |
            export/orgpedia_mahmar2024

      - name: checkout mahmed2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahmed2024
          path: import/mahmed2024
          sparse-checkout: |
            export/orgpedia_mahmed2024

      - name: checkout mahmin2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahmin2024
          path: import/mahmin2024
          sparse-checkout: |
            export/orgpedia_mahmin2024

      - name: checkout mahpar2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahpar2024
          path: import/mahpar2024
          sparse-checkout: |
            export/orgpedia_mahpar2024

      - name: checkout mahplan2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahplan2024
          path: import/mahplan2024
          sparse-checkout: |
            export/orgpedia_mahplan2024

      - name: checkout mahpwd2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahpwd2024
          path: import/mahpwd2024
          sparse-checkout: |
            export/orgpedia_mahpwd2024

      - name: checkout mahrev2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahrev2024
          path: import/mahrev2024
          sparse-checkout: |
            export/orgpedia_mahrev2024

      - name: checkout mahrural2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahrural2024
          path: import/mahrural2024
          sparse-checkout: |
            export/orgpedia_mahrural2024

      - name: checkout mahsanit2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahsanit2024
          path: import/mahsanit2024
          sparse-checkout: |
            export/orgpedia_mahsanit2024

      - name: checkout mahskill2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahskill2024
          path: import/mahskill2024
          sparse-checkout: |
            export/orgpedia_mahskill2024

      - name: checkout mahsoc2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahsoc2024
          path: import/mahsoc2024
          sparse-checkout: |
            export/orgpedia_mahsoc2024

      - name: checkout mahsoil2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahsoil2024
          path: import/mahsoil2024
          sparse-checkout: |
            export/orgpedia_mahsoil2024

      - name: checkout mahtech2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahtech2024
          path: import/mahtech2024
          sparse-checkout: |
            export/orgpedia_mahtech2024

      - name: checkout mahtour2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahtour2024
          path: import/mahtour2024
          sparse-checkout: |
            export/orgpedia_mahtour2024

      - name: checkout mahtrib2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahtrib2024
          path: import/mahtrib2024
          sparse-checkout: |
            export/orgpedia_mahtrib2024

      - name: checkout mahurb2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahurb2024
          path: import/mahurb2024
          sparse-checkout: |
            export/orgpedia_mahurb2024

      - name: checkout mahwater2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahwater2024
          path: import/mahwater2024
          sparse-checkout: |
            export/orgpedia_mahwater2024

      - name: checkout mahwom2024
        uses: actions/checkout@v4
        with:
          repository: orgpedia/mahwom2024
          path: import/mahwom2024
          sparse-checkout: |
            export/orgpedia_mahwom2024

      - name: import_export
        run: python3 import/src/import_data.py import GRs

      - name: Commit and push changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: actions export
        


